version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .  # The build context is the current directory
      dockerfile: Dockerfile  # Specify the Dockerfile if it's named differently or in a different location
    ports:
      - "1323:1323"
    # environment:
    #   PORTAL_GEO_LOCATION_ENABLED: true
    #   PORTAL_CLIENT_IP: "1.1.1.1"
    env_file:
      - .env.prod
    volumes:
      - ./data:/root/data
